export const brandsCollecton = [
  {
    id: 1,
    path: "https://www.bitzer.de/gb/en/",
    brandName: "Bitzer",
    img: "/brands/bitzer.jpg",
    bgColor: "bg-white",
  },
  {
    id: 2,
    path: "https://www.copeland.com/en-us",
    brandName: "Copeland",
    img: "/brands/copeland.png",
    bgColor: "bg-white",
  },
  {
    id: 3,
    path: "https://www.danfoss.com/en/",
    brandName: "Danfoss",
    img: "/brands/danfoss.svg",
  },
  {
    id: 4,
    path: "https://www.gea.com/en/",
    brandName: "GEA",
    img: "/brands/gea.svg",
    bgColor: "bg-white",
  },
  {
    id: 5,
    path: "https://mayekawa.com/",
    brandName: "MYCOM",
    img: "/brands/mycom.svg",
    bgColor: "bg-white",
  },
  {
    id: 6,
    path: "https://en.decsasrl.com/",
    brandName: "DECSA",
    img: "/brands/decsa.png",
    bgColor: "bg-white",
  },
  {
    id: 7,
    path: "https://baltimoreaircoil.com/",
    brandName: "Baltimore",
    img: "/brands/baltimore.jpg",
    bgColor: "bg-white",
  },
  {
    id: 8,
    path: "https://www.luvegroup.com/en/",
    brandName: "LU-VE Group",
    img: "/brands/luve.png",
    bgColor: "bg-white",
  },
  {
    id: 9,
    path: "https://www.friterm.com/",
    brandName: "FRITERM",
    img: "/brands/friterm.png",
    bgColor: "bg-white",
  },
  {
    id: 10,
    path: "https://www.modinecoolers.com/",
    brandName: "ECO Modine",
    img: "/brands/ecomodine.png",
    bgColor: "bg-white",
  },
  {
    id: 11,
    path: "https://www.castel.it/en/",
    brandName: "Castel",
    img: "/brands/castel.png",
    bgColor: "bg-neutral-700",
  },
  {
    id: 12,
    path: "https://www.se.com/ww/en/",
    brandName: "Schneider",
    img: "/brands/schneider.png",
    bgColor: "bg-white",
  },
  {
    id: 13,
    path: "https://pego.it/en/",
    brandName: "Pego",
    img: "/brands/pego.png",
    bgColor: "bg-zinc-800",
  },
  {
    id: 14,
    path: "https://global.abb/group/en",
    brandName: "ABB",
    img: "/brands/abb.png",
    bgColor: "bg-white",
  },
  {
    id: 15,
    path: "https://www.copeland.com/en-gb/brands/alco-controls",
    brandName: "Alco",
    img: "/brands/alco.png",
    bgColor: "bg-white",
  },
  {
    id: 16,
    path: "https://www.copeland.com/en-gb/brands/dixell",
    brandName: "Dixell",
    img: "/brands/dixell.svg",
    bgColor: "bg-white",
  },
  {
    id: 17,
    path: "https://termovent.com/",
    brandName: "Termovent",
    img: "/brands/termovent.svg",
    bgColor: "bg-neutral-900",
  },
  {
    id: 18,
    path: "https://www.daikin.com/",
    brandName: "Daikin",
    img: "/brands/daikin.svg",
    bgColor: "bg-white",
  },
  {
    id: 19,
    path: "https://www.lg.com/global/",
    brandName: "LG",
    img: "/brands/lg.svg",
    bgColor: "bg-stone-200",
  },
  {
    id: 20,
    path: "https://www.hitachi.com/",
    brandName: "HITACHI",
    img: "/brands/hitachi.png",
    bgColor: "bg-white",
  },
  {
    id: 21,
    path: "https://cabero.de/en",
    brandName: "CABERO",
    img: "/brands/cabero.svg",
    bgColor: "bg-white",
  },
  {
    id: 22,
    path: "https://global.aermec.com/en/",
    brandName: "AERMEC",
    img: "/brands/aermec.png",
    bgColor: "bg-white",
  },
];
